export const DAILY_AFFIRMATIONS = [
  {
    en: "I am at peace with all that has happened, is happening, and will happen.",
    zh: "我與所有已發生、正在發生和將要發生的事情和平共處。",
    es: "Estoy en paz con todo lo que ha sucedido, está sucediendo y sucederá.",
    author: "Buddhist Wisdom",
    authorZh: "佛學智慧",
    authorEs: "Sabiduría budista",
  },
  {
    en: "My thoughts are filled with positivity and my life is plentiful with prosperity.",
    zh: "我的思想充滿正能量，我的生活充滿富足。",
    es: "Mis pensamientos están llenos de positividad y mi vida rebosa prosperidad.",
    author: "Ancient Proverb",
    authorZh: "古老諺語",
    authorEs: "Proverbio antiguo",
  },
  {
    en: "Today, I abandon my old habits and take up new, more positive ones.",
    zh: "今天，我放下舊習慣，培養新的、更積極的習慣。",
    es: "Hoy dejo atrás mis viejos hábitos y adopto otros nuevos y más luminosos.",
    author: "Meditation Masters",
    authorZh: "冥想大師",
    authorEs: "Maestros de meditación",
  },
  {
    en: "I am the architect of my life; I build its foundation and choose its contents.",
    zh: "我是自己生命的建築師；我奠定它的基礎，選擇它的內容。",
    es: "Soy la arquitecta de mi vida; construyo sus cimientos y elijo su contenido.",
    author: "Spiritual Teaching",
    authorZh: "靈性教導",
    authorEs: "Enseñanza espiritual",
  },
  {
    en: "My body is healthy; my mind is brilliant; my soul is tranquil.",
    zh: "我的身體健康，我的心智敏銳，我的靈魂平靜。",
    es: "Mi cuerpo está sano, mi mente es clara y mi alma permanece serena.",
    author: "Holistic Wisdom",
    authorZh: "整體智慧",
    authorEs: "Sabiduría holística",
  },
  {
    en: "I am superior to negative thoughts and low actions.",
    zh: "我超越了負面思想和低級行為。",
    es: "Estoy por encima de los pensamientos negativos y de las acciones que me empequeñecen.",
    author: "Mindfulness Practice",
    authorZh: "正念修行",
    authorEs: "Práctica de mindfulness",
  },
  {
    en: "I have been given endless talents which I begin to utilize today.",
    zh: "我被賦予了無盡的天賦，今天我開始運用它們。",
    es: "He recibido talentos infinitos y hoy comienzo a ponerlos en práctica.",
    author: "Self-Realization",
    authorZh: "自我實現",
    authorEs: "Autorrealización",
  },
];
