export const FREE_DAILY_AI_GUIDANCE_LIMIT = 3;
export const VIP_DAILY_AI_GUIDANCE_LIMIT = 12;

export const AI_GUIDANCE_TOP_UP_COST_SINGLE = 3;
export const AI_GUIDANCE_TOP_UP_COST_BUNDLE = 8;

export const AI_GUIDANCE_TOP_UP_AMOUNT_SINGLE = 1;
export const AI_GUIDANCE_TOP_UP_AMOUNT_BUNDLE = 3;

