export const POST_AWAKENING_ARCS = [
  {
    id: "blessing-arc",
    zhTitle: "祝福之流",
    enTitle: "Blessing Arc",
    esTitle: "Arco de bendiciones",
    zhTheme: "把祝福送給朋友，建立回流與被接住的感覺。",
    enTheme: "Send blessings to friends and create a felt sense of return and connection.",
    esTheme: "Envía bendiciones a tus amigos y crea una sensación real de regreso y conexión.",
    zhReward: "靈魂星雲、無盡祈禱、更多社交型聖形",
    enReward: "Soul Nebula, Infinity Prayer, and more social sacred forms.",
    esReward: "Nebulosa del alma, plegaria infinita y más formas sagradas sociales.",
    metric: "blessingsSent",
    freeTarget: 3,
    vipTarget: 2,
  },
  {
    id: "ritual-arc",
    zhTitle: "儀式之路",
    enTitle: "Ritual Arc",
    esTitle: "Arco ritual",
    zhTheme: "讓冥想變成每日節奏，而不是完成新手期後就停下。",
    enTheme: "Turn meditation into a daily rhythm instead of stopping after onboarding.",
    esTheme: "Convierte la meditación en un ritmo diario en vez de detenerte tras la iniciación.",
    zhReward: "蓮華曼陀羅、鳳凰螺旋、更多儀式型內容",
    enReward: "Lotus Mandala, Phoenix Spiral, and more ritual-centered content.",
    esReward: "Mandala de loto, espiral del fénix y más contenido centrado en el ritual.",
    metric: "ritualDepth",
    freeTarget: 90,
    vipTarget: 70,
  },
  {
    id: "sacred-forms",
    zhTitle: "聖形之印",
    enTitle: "Sacred Forms",
    esTitle: "Formas sagradas",
    zhTheme: "把你的內在狀態顯化成更高階的形態收藏與花園記號。",
    enTheme: "Manifest your inner state into higher sacred form collections and garden marks.",
    esTheme: "Manifiesta tu estado interior en colecciones de formas sagradas más altas y marcas del jardín.",
    zhReward: "更多神聖幾何、星系與典藏級形態",
    enReward: "More sacred geometry, galaxy, and archive-grade forms.",
    esReward: "Más geometría sagrada, galaxias y formas de archivo.",
    metric: "formsUnlocked",
    freeTarget: 12,
    vipTarget: 10,
  },
] as const;
