export interface SpiritualQuote {
  zh: string;
  en: string;
  es?: string;
  author: string;
}

export const SPIRITUAL_QUOTES: SpiritualQuote[] = [
  {"zh":"你就是你正在尋找的答案。","en":"You are the answer you are looking for.","es":"Tú eres la respuesta que has estado buscando.","author":"奧修 Osho"},
  {"zh":"當下的力量，就是你本來的力量。","en":"The power of now is your original power.","es":"El poder del ahora es tu poder original.","author":"艾克哈特·托勒 Eckhart Tolle"},
  {"zh":"觀照呼吸，就是觀照生命本身。","en":"Watching the breath is watching life itself.","es":"Observar la respiración es observar la vida misma.","author":"克里希那穆提 J. Krishnamurti"},
  {"zh":"你不是思念中的人，你是看見思念的那個。","en":"You are not the person in the thoughts, you are the one seeing the thoughts.","es":"No eres la persona dentro de los pensamientos; eres quien los observa.","author":"尼斯卡伽達 Nisargadatta Maharaj"},
  {"zh":"真正的寧靜來自內在，而不是外在環境。","en":"True silence comes from within, not from the environment.","es":"El verdadero silencio nace dentro, no del entorno.","author":"拉瑪那·馬哈希 Ramana Maharshi"},
  {"zh":"放下「成為誰」的念頭，你就成為了全部。","en":"Drop the idea of becoming somebody, and you become all.","es":"Suelta la idea de convertirte en alguien y te vuelves todo.","author":"奧修 Osho"},
  {"zh":"愛不是佔有，愛是欣賞。","en":"Love is not possession, love is appreciation.","es":"El amor no es posesión; el amor es apreciación.","author":"奧修 Osho"},
  {"zh":"一切都是鏡子，你看到的都是你自己。","en":"Everything is a mirror. What you see is yourself.","es":"Todo es un espejo. Lo que ves eres tú mismo.","author":"魯米 Rumi"},
  {"zh":"痛苦是因為活在過去，快樂是因為活在未來，平安是因為活在當下。","en":"Pain is living in the past, pleasure in the future, peace in the present.","es":"El dolor vive en el pasado, el placer en el futuro y la paz en el presente.","author":"老子 Lao Tzu"},
  {"zh":"真正的自由是沒有選擇的自由。","en":"True freedom is freedom from choice.","es":"La verdadera libertad es la libertad de tener que elegir.","author":"克里希那穆提 J. Krishnamurti"},
  {"zh":"存在不需要理由，它本身就是理由。","en":"Existence needs no reason; it is the reason.","es":"La existencia no necesita razón; ella misma es la razón.","author":"奧修 Osho"},
  {"zh":"靜心不是停止思想，而是看見思想的流動。","en":"Meditation is not stopping thoughts, it is watching their flow.","es":"Meditar no es detener los pensamientos, sino observar su fluir.","author":"奧修 Osho"},
  {"zh":"你越放下，你越富有。","en":"The more you let go, the richer you become.","es":"Cuanto más sueltas, más rico te vuelves.","author":"老子 Lao Tzu"},
  {"zh":"覺醒不是獲得什麼，而是失去什麼。","en":"Awakening is not gaining something, it is losing something.","es":"Despertar no es ganar algo, sino perder algo.","author":"艾克哈特·托勒 Eckhart Tolle"},
  {"zh":"真相不是被相信的，真相是被活出來的。","en":"Truth is not to be believed; truth is to be lived.","es":"La verdad no es para creerla; la verdad es para vivirla.","author":"奧修 Osho"},
  {"zh":"當你完全接受此刻，一切掙扎都結束了。","en":"When you totally accept this moment, all struggle ends.","es":"Cuando aceptas por completo este momento, toda lucha termina.","author":"艾克哈特·托勒 Eckhart Tolle"},
  {"zh":"你是天空，思想只是過客的雲。","en":"You are the sky; thoughts are just passing clouds.","es":"Tú eres el cielo; los pensamientos son nubes pasajeras.","author":"奧修 Osho"},
  {"zh":"寧靜的心聽得見宇宙的低語。","en":"A quiet mind can hear the whispers of the universe.","es":"Una mente en silencio puede escuchar los susurros del universo.","author":"魯米 Rumi"},
  {"zh":"愛是你的本性，你只是忘記了。","en":"Love is your nature; you have just forgotten.","es":"El amor es tu naturaleza; solo lo habías olvidado.","author":"奧修 Osho"},
  {"zh":"活在當下，就是活在永恆。","en":"To live in the moment is to live in eternity.","es":"Vivir en el momento es vivir en la eternidad.","author":"老子 Lao Tzu"},
  {"zh":"你不需要變得更好，你只需要記起你本來就完美。","en":"You don't need to become better; you just need to remember you are already perfect.","es":"No necesitas volverte mejor; solo recordar que ya eres completo.","author":"奧修 Osho"},
  {"zh":"放下自我，你就找到了宇宙。","en":"Drop the ego, and you find the universe.","es":"Suelta el ego y encontrarás el universo.","author":"拉瑪那·馬哈希 Ramana Maharshi"},
  {"zh":"真正的富足是內在的滿足。","en":"True abundance is inner contentment.","es":"La verdadera abundancia es el contento interior.","author":"老子 Lao Tzu"},
  {"zh":"每一次呼吸都是一次新生。","en":"Every breath is a rebirth.","es":"Cada respiración es un renacer.","author":"釋迦牟尼 Buddha"},
  {"zh":"你就是那個你一直在等待的人。","en":"You are the one you have been waiting for.","es":"Tú eres la persona que has estado esperando.","author":"奧修 Osho"},
  {"zh":"存在愛你，它從未停止過。","en":"Existence loves you; it has never stopped.","es":"La existencia te ama; nunca ha dejado de hacerlo.","author":"奧修 Osho"},
  {"zh":"當你不再尋找，答案就出現了。","en":"When you stop searching, the answer appears.","es":"Cuando dejas de buscar, la respuesta aparece.","author":"尼斯卡伽達 Nisargadatta"},
  {"zh":"你就是光，只是忘記打開開關。","en":"You are the light; you just forgot to turn it on.","es":"Tú eres la luz; solo olvidaste encenderla.","author":"奧修 Osho"},
  {"zh":"真正的祈禱是感恩，不是乞求。","en":"Real prayer is gratitude, not begging.","es":"La oración verdadera es gratitud, no súplica.","author":"奧修 Osho"},
  {"zh":"生命是一場慶典，你是唯一的嘉賓。","en":"Life is a celebration, and you are the only guest.","es":"La vida es una celebración y tú eres el invitado principal.","author":"奧修 Osho"},
  {"zh":"覺知就是解脫。","en":"Awareness is liberation.","es":"La consciencia es liberación.","author":"克里希那穆提 J. Krishnamurti"},
  {"zh":"你不需要去任何地方，你已經在家了。","en":"You don't need to go anywhere; you are already home.","es":"No necesitas ir a ningún lugar; ya estás en casa.","author":"釋迦牟尼 Buddha"},
  {"zh":"愛是唯一的宗教。","en":"Love is the only religion.","es":"El amor es la única religión.","author":"奧修 Osho"},
  {"zh":"靜心是回到源頭的路。","en":"Meditation is the way back to the source.","es":"La meditación es el camino de regreso a la fuente.","author":"老子 Lao Tzu"},
  {"zh":"你就是奇蹟。","en":"You are the miracle.","es":"Tú eres el milagro.","author":"艾克哈特·托勒 Eckhart Tolle"},
  {"zh":"放下過去，放下未來，你就擁有了永恆。","en":"Drop the past, drop the future, and you have eternity.","es":"Suelta el pasado, suelta el futuro y tendrás la eternidad.","author":"奧修 Osho"},
  {"zh":"存在從不匆忙，因為它已經到達了。","en":"Existence is never in a hurry; it has already arrived.","es":"La existencia nunca tiene prisa; ya ha llegado.","author":"老子 Lao Tzu"},
  {"zh":"真正的快樂是無原因的。","en":"Real happiness is without reason.","es":"La felicidad verdadera no necesita motivo.","author":"尼斯卡伽達 Nisargadatta"},
  {"zh":"你就是道路，也是目的地。","en":"You are the path and the destination.","es":"Tú eres el camino y también el destino.","author":"魯米 Rumi"},
  {"zh":"活著就是冥想。","en":"To be alive is to meditate.","es":"Estar vivo ya es meditar.","author":"克里希那穆提 J. Krishnamurti"},
  {"zh":"愛是讓你成為自己的鑰匙。","en":"Love is the key that makes you yourself.","es":"El amor es la llave que te permite ser tú mismo.","author":"奧修 Osho"},
  {"zh":"當你完全在當下，時間消失了。","en":"When you are totally in the moment, time disappears.","es":"Cuando estás por completo en el instante, el tiempo desaparece.","author":"艾克哈特·托勒 Eckhart Tolle"},
  {"zh":"你是無限的，只是被有限的身體困住了。","en":"You are infinite, just trapped in a finite body.","es":"Eres infinito; solo estás temporalmente contenido en un cuerpo finito.","author":"奧修 Osho"},
  {"zh":"真正的智慧是知道自己一無所知。","en":"True wisdom is knowing that you know nothing.","es":"La verdadera sabiduría es saber que no sabes nada.","author":"蘇格拉底 Socrates"},
  {"zh":"每一天都是新的開始。","en":"Every day is a new beginning.","es":"Cada día es un nuevo comienzo.","author":"達賴喇嘛 Dalai Lama"},
  {"zh":"寧靜的心不需要答案，因為它就是答案。","en":"A silent mind needs no answers; it is the answer.","es":"Una mente silenciosa no necesita respuestas, porque ella misma es la respuesta.","author":"拉瑪那·馬哈希 Ramana Maharshi"},
  {"zh":"你就是宇宙在體驗自己。","en":"You are the universe experiencing itself.","es":"Tú eres el universo experimentándose a sí mismo.","author":"艾倫·瓦茲 Alan Watts"},
  {"zh":"愛是唯一的自由。","en":"Love is the only freedom.","es":"El amor es la única libertad.","author":"奧修 Osho"},
  {"zh":"活在當下，就是活出了永恆。","en":"Living in the moment is living eternity.","es":"Vivir este momento es vivir la eternidad.","author":"老子 Lao Tzu"},
  {"zh":"當下的每一刻，都是最好的禮物。","en":"Every moment of now is the best gift.","es":"Cada instante del ahora es el mejor regalo.","author":"釋迦牟尼 Buddha"}
];
